config/routes.rb
Rails.application.routes.draw do


  get 'sessions/new'

  get 'welcome/hello'
  root 'welcome#hello'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

   get '/users/:id/edit' => 'users#edit'
   patch '/users/:id/edit' => 'users#update'
  patch '/users/:id' => 'users#update'
  resources :users

  get '/cars/new' => 'cars#new'
  get '/cars/:id' => 'cars#show'
  resources :cars


  resources :bookings do
    member do
      put 'pickup'
      put 'returncar'
      put 'cancel'
    end
  end
    patch 'bookings/:id/cancel' => 'reservations#cancel'
  post 'bookings/:id/cancel' => 'reservations#cancel'
end

app/models/user.rb
class User < ApplicationRecord
  enum roles: [:Customer, :Admin, :SuperAdmin]
  before_save { self.email = email.downcase }
  validates :firstname,  presence: true, length: { maximum: 20 }
  validates :lastname, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :phone, presence: true, length: { maximum: 10, minimum: 10 }, allow_nil: true
  validates :licenseN, presence: true, length: { maximum: 9, minimum: 9 },
                    uniqueness: true, allow_nil: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    
    BCrypt::Password.create(string, cost: cost)
  end
  
  def admin?
    self.role == 'Admin'
  end
  
  def superadmin?
    self.role = 'SuperAdmin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:index, :show, :edit, :update]

  def show
    @user = User.find(params[:id])
    @q_bookings = Booking.ransack(params[:q])
    @bookings = @q_bookings.result().where(:user_id => session[:user_id]).paginate(page: params[:page]) || [] # return current users record or empty
  end

  def new
    @user = User.new
  end

  def index
    @users = @q_users.result().paginate(page: params[:page])

  end

  def after_sign_in_path_for(resource)
  current_user_path
  end

  def show
    @user = User.find(params[:id])
    @q_bookings = Booking.ransack(params[:q])
    @bookings = @q_bookings.result().where(:user_id => session[:user_id]).paginate(page: params[:page]) || [] # return current users record or empty

  end

  def create
    @user = User.new(user_params)
    if @user.save
      if logged_in?
        flash[:success] = "Account created!"
      else
        log_in @user
        flash[:success] = "Welcome to Unter!"
      end
      redirect_to @user
    else
      flash[:danger] = "Sign up Fail"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :phone, :licenseN,
                                    :password, :password_confirmation, :role, :rentalCharge)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.firstname, class: "gravatar")
  end
  def user_fields 
    # fields to be displayed on front-end view
    [:firstname, :lastname, :email, :phone, :licenseN, :role, :rentalCharge, :available] 
  end
    
  def action 
    action_name == 'advanced_search' ? :post : :get 
  end
  
  def display_user_sorted_column_headers(search) 
    user_fields.each_with_object('') do |field, string| 
      string << content_tag(:th, sort_link(search, field, {}, method: action), class: 'thead-default') 
    end 
  end
  
  def display_user_search_results(objects) 
    objects.each_with_object('') do |object, string| 
      string << content_tag(:tr, display_user_search_results_row(object)) 
    end 
  end
  
  def display_user_search_results_row(object)
    fieldCount = 0
    user_fields.each_with_object('') do |field, string|
      if fieldCount == 0
        string << content_tag(:td, link_to(object.send(field), '/users/' + object.id.to_s))
      elsif field == :rentalCharge
        string << content_tag(:td, "%.2f"%object.send(field))
      else
        string << content_tag(:td, object.send(field))
      end
      
      fieldCount += 1
      
    end
    .html_safe
  end
    
end

app/views/users/_form.html.erb
<div class="form-group">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
          </div>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :email %>
      <%= f.email_field :email %>
      <br>
      <% if !logged_in? || current_user?(@user) %>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <br>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>
        <br>
      <% else %>
        <%= f.hidden_field :password, value: "123456" %>
        <%= f.hidden_field :password_confirmation, value: "123456" %>
      <% end %>
      <% if isAdmin? || isSuperAdmin? %>
        <%= f.label :rentalCharge %>
        <%= f.number_field :rentalCharge, min: 0, step: 0.01 %><br>
      <% end %>
      <% if logged_in? && isAdmin? %>
        <%= f.label :role %>
        <%= f.collection_select :role, User.roles.except(:SuperAdmin), :first, :first, {:prompt => "Please select role"} %><br>
        <%= f.label "Available to rent car" %>
        <%= f.collection_select :available, {false=>0, true=>1}, :first, :first, {:prompt => "Please select role"} %><br>
      <% elsif logged_in? && isSuperAdmin? %>
        <%= f.label :role %>
        <%= f.collection_select :role, User.roles, :first, :first, {:prompt => "Please select role"} %><br>
        <%= f.label "Available to rent car" %>
        <%= f.collection_select :available, {false=>0, true=>1}, :first, :first, {:prompt => "Please select role"} %><br>
      <% end %>
      <br>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: edit_user_path) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label "First Name" %>
      <%= f.text_field :firstname, class: 'form-control' %>
      
      <%= f.label "Last name" %>
      <%= f.text_field :lastname, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.text_field :phone, class: 'form-control' %>
      
      <%= f.label "License Number" %>
      <%= f.text_field :licenseN, class: 'form-control' %>
     
      <br />
      <p .text_primary>Leave password and confirmation fields blank to keep current password</p>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %> 
      
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign Up</h1>
<div class="row">
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 text-left">

    <%= form_for(:user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label "First name" %>
      <div class="row">  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <%= f.text_field :firstname, class: 'form-control' %></div></div>

      <%= f.label "Last name" %>
      <div class="row">  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <%= f.text_field :lastname, class: 'form-control' %></div></div>

      <%= f.label :email %>
      <div class="row">  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <%= f.email_field :email, class: 'form-control' %></div></div>

      <%= f.label :phone %>
      <div class="row">  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
      <%= f.text_field :phone, class: 'form-control' %></div></div>

      <%= f.label "License Number" %>
      <div class="row">  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
      <%= f.text_field :licenseN, class: 'form-control' %></div></div>

      <%= f.label :password %>
      <div class="row">  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <%= f.password_field :password, class: 'form-control' %></div></div>

      <%= f.label :password_confirmation, "Confirmation" %>
      <div class="row">  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <%= f.password_field :password_confirmation, class: 'form-control' %></div></div>

      <div class="row"><div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
      <%= f.submit "Submit", class: "btn btn-primary" %></div></div>
    <% end %>

  </div>
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.id) %>

  <div class="row">
    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2"></div>
    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
      <h1><%= @user.firstname%> <%= @user.lastname %></h1>

      <div class="row headings">
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 "><h2>User Details</h2></div>
        <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9"><h2>Current Bookings</h2></div>
      </div>
      <div class="row">
      <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 text-left">
          <p>
          <%= label_tag "name" %>: <%= @user.firstname%> <%= @user.lastname %><br>
          <%= label_tag :email %>: <%= @user.email %><br>
          <%= label_tag :phone %>: <%= @user.phone %> <br>
          <%= label_tag "license" %>: <%= @user.licenseN %> <br>
          <%= label_tag "Total rental charge" %>: <%= '%.2f' % @user.rentalCharge %><br>
          <%= label_tag "Available to rent car?" %> <%= (@user.available)? "Yes": "No" %>
        </p>
        <%= link_to "Update Details", edit_user_path(current_user), class: "btn btn-lg btn-primary" %>
      </div>
      <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
        <% if current_bookings(@bookings) %>
        <%= content_tag :table, class: 'table' do %>
          <%= content_tag :thead, display_booking_sorted_column_headers(@q_bookings), nil, false  %>
          <%= content_tag :tbody, display_booking_search_results_current(@bookings), nil, false  %>
        <% end %>
        <%else %>
        <%= content_tag :h4, "No current bookings" %>
        <%end %>
        <h2>Past Bookings</h2>
        <%= content_tag :table, class: 'table' do %>
          <%= content_tag :thead, display_booking_sorted_column_headers(@q_bookings), nil, false  %>
          <%= content_tag :tbody, display_booking_search_results_past(@bookings), nil, false  %>
        <% end %>
        <%= link_to "New Bookings", cars_path, class: "btn btn-lg btn-primary" %>
        <%= link_to "View all Bookings", bookings_path, class: "btn btn-lg btn-primary" %>
      </div>
    </div>
    </div>
    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2"></div>
  </div>