config/routes.rb
Rails.application.routes.draw do


  get 'sessions/new'

  get 'welcome/hello'
  root 'welcome#hello'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

   get '/users/:id/edit' => 'users#edit'
   patch '/users/:id/edit' => 'users#update'
  patch '/users/:id' => 'users#update'
  resources :users

  get '/cars/new' => 'cars#new'
  get '/cars/:id' => 'cars#show'
  resources :cars


  resources :bookings do
    member do
      put 'pickup'
      put 'returncar'
      put 'cancel'
    end
  end
    patch 'bookings/:id/cancel' => 'reservations#cancel'
  post 'bookings/:id/cancel' => 'reservations#cancel'
end

app/models/car.rb
class Car < ApplicationRecord
  
  enum sizes: [:Small, :Medium, :Big]
  enum statuses: [:CheckedOut, :Available, :Reserved, :Suggested]
  
  validates :make, presence: true
  validates :model, presence: true
  validates :year, presence: true
  validates :size, presence: true
  validates :price, presence: true
  
  def isAvailable?
    status == "Available"
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

   before_action :logged_in_user, only: [:index, :new, :show]
<<<<<<< HEAD
   before_action :logged_in_as_admin, only: [:new, :destroy, :edit, :update]
=======

>>>>>>> d673e81754df5b8f57b5db36836921c22588c963
  def index
    @cars_list = Car.all
    @q_cars = Car.ransack(params[:q])
    @cars = @q_cars.result().paginate(page: params[:page])

  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @car = Car.find_by(params[:id])
  end
  def destroy
    @car = Car.find_by(params[:id])
    reservations = Reservation.where(car_id: @car.id)
    reservations.destroy_all
    @car.destroy
    flash[:success] = 'Car deleted.'
    redirect_to cars_url
  end
  private

    def car_params
      params.require(:car).permit(:make, :model, :year, :size, :price, :location, :status)
    end

end

app/helpers/cars_helper.rb
module CarsHelper
  def car_fields 
    # fields to be displayed on front-end view
    [:make, :model, :status, :year, :price, :size, :location, :status] 
  end
    
  def action 
    action_name == 'advanced_search' ? :post : :get 
  end
  
  def display_car_sorted_column_headers(search) 
    car_fields.each_with_object('') do |field, string| 
      string << content_tag(:th, sort_link(search, field, {}, method: action)) 
    end 
  end
  
  def display_car_search_results(objects) 
    objects.each_with_object('') do |object, string| 
      string << content_tag(:tr, display_car_search_results_row(object)) 
    end 
  end
  
  def display_car_search_results_row(object)
    fieldCount = 0
    car_fields.each_with_object('') do |field, string|
      if fieldCount == 0
        string << content_tag(:td, link_to(object.send(field), '/cars/' + object.id.to_s))
      else
        string << content_tag(:td, object.send(field))
      end
      
      fieldCount += 1
      
    end
    .html_safe
  end
  
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
      <% if @car.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            The form contains <%= pluralize(@car.errors.count, "error") %>.
          </div>
          <ul>
          <% @car.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <%= f.label :licensePlateNumber %>
      <%= f.text_field :licensePlateNumber %>
      <br>
      <%= f.label :manufacturer %>
      <%= f.text_field :manufacturer %>
      <br>
      <%= f.label :model %>
      <%= f.text_field :model %>
      <br>
      <% if isAdmin? || isSuperAdmin? %>
        <%= f.label :hourlyRentalRate %>
        <%= f.number_field :hourlyRentalRate, min: 0, step: 0.01 %><br>
      <% elsif isCustomer? %>
        <%= f.hidden_field :hourlyRentalRate, value: 0 %>
      <% end %>
      <%= f.label :style %>
      <%= f.collection_select :style, Car.styles, :first, :first, {:prompt => "Please select car status"} %>
      <br>
      <%= f.label :location %>
      <%= f.text_field :location %>
      <br>
      <% if isAdmin? || isSuperAdmin? %>
        <%= f.label :status %>
        <%= f.collection_select :status, Car.statuses, :first, :first, {:prompt => "Please select car status"} %><br>
      <% elsif isCustomer? %>
        <%= f.hidden_field :status, value: :Suggested %>
      <% end %>
      
      <%= f.submit "Submit car info", class: "btn btn-primary" %>
    <% end %>`

app/views/cars/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Edit car info</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<% provide(:title, 'All cars') %>
<h1>View and Search cars</h1>

<%= search_form_for @q_cars do |f| %>
  <%= f.label :location %>
  <%= f.search_field :location_cont %><br>
  <%= f.label :manufacturer %>
  <%= f.collection_select :make_cont, Car.select("distinct make"), :make, :make, {:include_blank => "Please select car maker"} %><br>
  <%= f.label :model %>
  <%= f.collection_select :model_cont, Car.select("distinct model"), :model, :model, {:include_blank => "Please select car model"} %><br>
  <%= f.label :style %>
  <%= f.collection_select :size_cont, Car.sizes, :first, :first, {:include_blank => "Please select car style"} %><br>
  <%= f.label :status %>
  
  <%= f.collection_select :status_cont, Car.statuses.except(:Suggested), :first, :first, {:include_blank => "Please select car status"} %><br>
  <%= f.submit "Search", class: "btn btn-primary" %>
<% end %>

<%= will_paginate %>
<%= content_tag :table, class: 'table' do %>
  <%= content_tag :thead, display_car_sorted_column_headers(@q_cars), nil, false %>
  <%= content_tag :tbody, display_car_search_results(@cars), nil, false %>
<% end %>
<%= will_paginate %>

app/views/cars/show.html.erb
<% provide(:title, @car.make+' - '+@car.model) %>

<h1>
  <%= @car.make %>
</h1>
<div class="row">
  <aside class="col-md-4">
    <section class="car_info">
      
        <%= label_tag "Model" %> :
        <%= @car.model %><br>
        <%= label_tag "Year" %> :
        <%= @car.year %><br>
        <%= label_tag "Price(p/h)" %> :
        <%= '$%.2f per hour' % @car.price %><br>
        <%= label_tag "Size" %> :
        <%= @car.size %><br>
        <%= label_tag "Location" %> :
        <%= @car.location %><br>
        <%= label_tag "Status" %> :
        <%= @car.status %><br>
      
    </section>
  </aside>
</div>

<% if @car.isAvailable? %>
  <%= link_to 'Book', new_booking_path(:car_id => @car.id) %> |
<% end %>
<% if isAdmin? || isSuperAdmin? %>
  
    <%= link_to 'Edit', edit_car_path(@car) %> |
  
  <%= link_to "Delete", @car, method: :delete, data: { confirm: "Delete this car?" } %> |
<% end %>
<%= link_to 'List', cars_path %> |
<%= link_to 'Back', :back %>