config/routes.rb
Rails.application.routes.draw do


  get 'sessions/new'

  get 'welcome/hello'
  root 'welcome#hello'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

   get '/users/:id/edit' => 'users#edit'
   patch '/users/:id/edit' => 'users#update'
  patch '/users/:id' => 'users#update'
  resources :users

  get '/cars/new' => 'cars#new'
  get '/cars/:id' => 'cars#show'
  resources :cars


  resources :bookings do
    member do
      put 'pickup'
      put 'returncar'
      put 'cancel'
    end
  end
    patch 'bookings/:id/cancel' => 'reservations#cancel'
  post 'bookings/:id/cancel' => 'reservations#cancel'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unter</title>
    <%= csrf_meta_tags %>

    <%= include_gon %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:gmapsHead) %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCOARHaYAOUzRECf21AurlwNQHeLDLtgOA&libraries=places&callback=initAutocomplete" async="async" defer="defer"></script>
  </head>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to image_tag("logo_nav.jpg", border: 0, height: '50'), root_path, id: "logo", class: "navbar-left" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Book", cars_path %></li>
          <%if logged_in? %>
            <li><%= link_to "Profile", current_user %></li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>

        </ul>
      </nav>
    </div>
  </header>

  <body>
    <div class="container-fluid">
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2"></div>
      <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2"></div>
    </div>
    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
</html>